package com.yuanye.njdt.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yuanye.njdt.data.entity.ExampleEntity;
import com.yuanye.njdt.data.entity.PdfDownEntity;
import com.yuanye.njdt.data.entity.PlanEntity;

import com.yuanye.njdt.db.ExampleEntityDao;
import com.yuanye.njdt.db.PdfDownEntityDao;
import com.yuanye.njdt.db.PlanEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exampleEntityDaoConfig;
    private final DaoConfig pdfDownEntityDaoConfig;
    private final DaoConfig planEntityDaoConfig;

    private final ExampleEntityDao exampleEntityDao;
    private final PdfDownEntityDao pdfDownEntityDao;
    private final PlanEntityDao planEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exampleEntityDaoConfig = daoConfigMap.get(ExampleEntityDao.class).clone();
        exampleEntityDaoConfig.initIdentityScope(type);

        pdfDownEntityDaoConfig = daoConfigMap.get(PdfDownEntityDao.class).clone();
        pdfDownEntityDaoConfig.initIdentityScope(type);

        planEntityDaoConfig = daoConfigMap.get(PlanEntityDao.class).clone();
        planEntityDaoConfig.initIdentityScope(type);

        exampleEntityDao = new ExampleEntityDao(exampleEntityDaoConfig, this);
        pdfDownEntityDao = new PdfDownEntityDao(pdfDownEntityDaoConfig, this);
        planEntityDao = new PlanEntityDao(planEntityDaoConfig, this);

        registerDao(ExampleEntity.class, exampleEntityDao);
        registerDao(PdfDownEntity.class, pdfDownEntityDao);
        registerDao(PlanEntity.class, planEntityDao);
    }
    
    public void clear() {
        exampleEntityDaoConfig.clearIdentityScope();
        pdfDownEntityDaoConfig.clearIdentityScope();
        planEntityDaoConfig.clearIdentityScope();
    }

    public ExampleEntityDao getExampleEntityDao() {
        return exampleEntityDao;
    }

    public PdfDownEntityDao getPdfDownEntityDao() {
        return pdfDownEntityDao;
    }

    public PlanEntityDao getPlanEntityDao() {
        return planEntityDao;
    }

}
